# Generated by Django 5.0.6 on 2024-07-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/country_images/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/hospital_images/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='file_upload',
            field=models.FileField(upload_to='static/upload_files/'),
        ),
    ]
