# Generated by Django 5.0.6 on 2024-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_country_image_alter_hospital_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('one_line_description', models.CharField(max_length=255)),
                ('front_image', models.ImageField(upload_to='service_images/')),
                ('main_content', models.TextField()),
            ],
        ),
    ]
