# Generated by Django 5.0.6 on 2024-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
