# Generated by Django 5.0.6 on 2024-08-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_patientprofile_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalopinionrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalopinionrequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalopinionrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='MedicalOpinionRequest',
        ),
        migrations.DeleteModel(
            name='MedicalReport',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='QuoteRequest',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
