# Generated by Django 5.0.6 on 2024-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_medicalreport_doctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
